k9:
  fqdn: k9.midorlo.com
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    hikari:
      pool-name: k9
      password: k9
      username: k9
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/dev?currentSchema=security
    password: dev
    username: dev
springdoc:
  version: 1
  api-docs:
    groups:
      enabled: true
    resolve-schema-properties: true
  auto-tag-classes: true
  packages-to-scan:
    - com.midorlo.k9.rest
  enable-native-image-support: true
  show-actuator: false
  swagger-ui:
    show-common-extensions: true
server:
  port: 3000
management:
  # Enable every Actuator endpoint.
  endpoint:
    shutdown:
      enabled: true
logging:
  # Debug logging for own scope.
  level:
    com:
      midorlo:
        k9: DEBUG